DROP TABLE IF EXISTS tb_herois;
CREATE TABLE tb_herois (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER   NOT Null
)

DELETE FROM tb_herois WHERE id = 2;

SELECT * FROM tb_heroi;

